export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface-container": "#efeeea",
              "on-tertiary-fixed-variant": "#584144",
              "tertiary-container": "#584144",
              "on-error-container": "#93000a",
              "primary-fixed-dim": "#e7bdb1",
              "on-secondary-fixed-variant": "#4f4538",
              "on-background": "#1b1c1a",
              "on-primary-container": "#d4ada1",
              "secondary-container": "#efe0cd",
              "on-tertiary": "#ffffff",
              "on-tertiary-container": "#cdaeb1",
              "secondary-fixed": "#efe0cd",
              "tertiary-fixed-dim": "#debfc2",
              "error": "#ba1a1a",
              "surface-container-highest": "#e4e2de",
              "surface-variant": "#e4e2de",
              "surface-container-low": "#f5f3ef",
              "on-primary-fixed": "#2c160e",
              "on-secondary-container": "#6d6354",
              "on-secondary": "#ffffff",
              "surface": "#fbf9f5",
              "outline-variant": "#d4c3be",
              "background": "#fbf9f5",
              "surface-container-high": "#eae8e4",
              "surface-dim": "#dbdad6",
              "inverse-surface": "#30312e",
              "outline": "#827470",
              "primary-fixed": "#ffdbd0",
              "secondary": "#675d4e",
              "secondary-fixed-dim": "#d2c4b2",
              "tertiary": "#402b2e",
              "on-primary-fixed-variant": "#5d4037",
              "surface-bright": "#fbf9f5",
              "on-tertiary-fixed": "#281719",
              "surface-tint": "#77574d",
              "on-surface-variant": "#504441",
              "primary-container": "#5d4037",
              "inverse-on-surface": "#f2f0ed",
              "surface-container-lowest": "#ffffff",
              "on-surface": "#1b1c1a",
              "inverse-primary": "#e7bdb1",
              "primary": "#442a22",
              "error-container": "#ffdad6",
              "on-primary": "#ffffff",
              "on-secondary-fixed": "#221a0f",
              "tertiary-fixed": "#fcdbde",
              "on-error": "#ffffff"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "base": "8px",
              "section-gap": "80px",
              "gutter": "24px",
              "margin-desktop": "64px",
              "container-max": "1280px",
              "margin-mobile": "20px"
      },
      "fontFamily": {
              "headline-xl-mobile": ["Playfair Display"],
              "body-sm": ["Montserrat"],
              "body-md": ["Montserrat"],
              "headline-lg": ["Playfair Display"],
              "headline-md": ["Playfair Display"],
              "body-lg": ["Montserrat"],
              "headline-xl": ["Playfair Display"],
              "label-md": ["Montserrat"],
              "label-lg": ["Montserrat"]
      },
      "fontSize": {
              "headline-xl-mobile": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "headline-lg": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
              "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "headline-xl": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-md": ["12px", {"lineHeight": "1.0", "fontWeight": "500"}],
              "label-lg": ["14px", {"lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
